#pragma once
#include <injector/defines.hpp>

namespace INJECTOR_NAMESPACE
{
    enum class BufferUsage
    {
        UniformTexel,
        StorageTexel,
        Uniform,
        Storage,
        Index,
        Vertex,
        Indirect,
        TransformFeedback,
        TransformFeedbackCounterBuffer,
    };

    /*Array = GL_ARRAY_BUFFER, // GL 2.0
        AtomicCounter = GL_ATOMIC_COUNTER_BUFFER, // GL 4.3
        CopyRead = GL_COPY_READ_BUFFER, // GL 3.1
        CopyWrite = GL_COPY_WRITE_BUFFER, // GL 2.0
        DrawIndirect = GL_DRAW_INDIRECT_BUFFER, // GL 2.0
        ElementArray = GL_ELEMENT_ARRAY_BUFFER, // GL 2.0
        PixelPack = GL_PIXEL_PACK_BUFFER, // GL 2.0
        PixelUnpack = GL_PIXEL_UNPACK_BUFFER, // GL 2.0
        Texture = GL_TEXTURE_BUFFER, // GL 3.1
        TransformFeedback = GL_TRANSFORM_FEEDBACK_BUFFER, // GL 2.0
        Uniform = GL_UNIFORM_BUFFER, // GL 3.1*/

   /* VK_BUFFER_USAGE_TRANSFER_SRC_BIT = 0x00000001,
        VK_BUFFER_USAGE_TRANSFER_DST_BIT = 0x00000002,
        VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000004,
        VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 0x00000008,
        VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT = 0x00000010,
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT = 0x00000020,
        VK_BUFFER_USAGE_INDEX_BUFFER_BIT = 0x00000040,
        VK_BUFFER_USAGE_VERTEX_BUFFER_BIT = 0x00000080,
        VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT = 0x00000100,
        VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT = 0x00020000,
        VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT = 0x00000800,
        VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT = 0x00001000,
        VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT = 0x00000200,
        VK_BUFFER_USAGE_RAY_TRACING_BIT_KHR = 0x00000400,
        VK_BUFFER_USAGE_RAY_TRACING_BIT_NV = VK_BUFFER_USAGE_RAY_TRACING_BIT_KHR,
        VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT = VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,
        VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_KHR = VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,
        VK_BUFFER_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF*/
}
